# Generated by Django 5.1.3 on 2025-01-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField()),
                ("headline", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("url", models.URLField(max_length=500)),
                ("source", models.CharField(max_length=200)),
            ],
        ),
    ]
