# Generated by Django 5.1.3 on 2025-01-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newsitem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="is_positive",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="sentiment_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
