# Generated by Django 5.1.3 on 2025-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newsitem_is_positive_newsitem_sentiment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="sentiment_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
