# Generated by Django 5.1.3 on 2025-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_newsitem_sentiment_score"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("is_positive", True), ("sentiment_score__gte", 0)),
                        models.Q(("is_positive", False), ("sentiment_score__lt", 0)),
                        _connector="OR",
                    )
                ),
                name="sentiment_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sentiment_score__gte", -1), ("sentiment_score__lte", 1)),
                    ("sentiment_score__isnull", True),
                    _connector="OR",
                ),
                name="sentiment_score_is_in_range_from_-1_to_1",
            ),
        ),
    ]
