# Generated by Django 5.1.3 on 2025-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "news",
            "0007_remove_newsitem_sentiment_score_is_in_range_from__1_to_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
