# Generated by Django 5.1.3 on 2024-12-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
