# Generated by Django 5.1.3 on 2025-01-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0004_rename_timestamp_trade_enter_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlistitem",
            name="watchlist",
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
        migrations.DeleteModel(
            name="WatchlistItem",
        ),
    ]
