# Generated by Django 5.1.3 on 2025-02-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_remove_watchlistitem_watchlist_delete_watchlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="enter_date",
            field=models.DateTimeField(),
        ),
    ]
