# Generated by Django 5.1.3 on 2025-02-11 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0007_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="markets.strategy",
            ),
        ),
    ]
