# Generated by Django 5.1.3 on 2025-02-13 18:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0011_alter_strategy_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(("enter_price__gt", 0)),
                name="enter_price_must_be_greater_than_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="amount_must_be_greater_than_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "enter_date__lte",
                        datetime.datetime(2025, 2, 13, 20, 22, 59, 981917),
                    )
                ),
                name="enter_date_must_be_in_the_past",
            ),
        ),
    ]
