# Generated by Django 5.1.3 on 2025-02-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0012_trade_enter_price_must_be_greater_than_0_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trade",
            name="enter_date_must_be_in_the_past",
        ),
    ]
